# fly.toml app configuration file generated for chatbot23 on 2023-06-13T16:52:19+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-builder-proud-breeze-7008"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]